# Site settings
title: e.Quanta
email: eQ@gmail.com
url: https://github.com/leroy1977/eQ
description: "Diligentia laborat omnis silvae et maria"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#305c66'

# Footer settings
footer: eQuanta, diligentia laborat omnis silvae et maria.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/eQuanta.env/

# Build settings
markdown: kramdown
permalink: pretty
